service: serverless-blog-api
frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-south-1

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: '*'
